// <auto-generated />
namespace Cs_Notas.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RegimesAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegimesAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201612131301590_RegimesAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
