// <auto-generated />
namespace Cs_Notas.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Configuracoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Configuracoes));
        
        string IMigrationMetadata.Id
        {
            get { return "201607261807079_Configuracoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
