//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PEDIDO {
    
    private PEDIDOREGISTRO[] rEGISTROField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("REGISTRO")]
    public PEDIDOREGISTRO[] REGISTRO {
        get {
            return this.rEGISTROField;
        }
        set {
            this.rEGISTROField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PEDIDOREGISTRO {
    
    private string cANCELAMENTODEINDISPONIBILIDADEField;
    
    private string cANCELAMENTO_TIPOField;
    
    private string cANCELAMENTO_DATAField;
    
    private string pROTOCOLOINDISPONIBILIDADEField;
    
    private string dATAPEDIDOField;
    
    private string nUMERODOPROCESSOField;
    
    private string tELEFONEField;
    
    private string nOMEINSTITUICAOField;
    
    private string fORUMVARAField;
    
    private string uSUARIOField;
    
    private string eMAILField;
    
    private PESSOASINDIVIDUO[] iNDISPONIBILIDADEField;
    
    private PESSOASINDIVIDUO[] cANCELAMENTOField;
    
    private string hASHVISUALIZACAOField;
    
    /// <remarks/>
    public string CANCELAMENTODEINDISPONIBILIDADE {
        get {
            return this.cANCELAMENTODEINDISPONIBILIDADEField;
        }
        set {
            this.cANCELAMENTODEINDISPONIBILIDADEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string CANCELAMENTO_TIPO {
        get {
            return this.cANCELAMENTO_TIPOField;
        }
        set {
            this.cANCELAMENTO_TIPOField = value;
        }
    }
    
    /// <remarks/>
    public string CANCELAMENTO_DATA {
        get {
            return this.cANCELAMENTO_DATAField;
        }
        set {
            this.cANCELAMENTO_DATAField = value;
        }
    }
    
    /// <remarks/>
    public string PROTOCOLOINDISPONIBILIDADE {
        get {
            return this.pROTOCOLOINDISPONIBILIDADEField;
        }
        set {
            this.pROTOCOLOINDISPONIBILIDADEField = value;
        }
    }
    
    /// <remarks/>
    public string DATAPEDIDO {
        get {
            return this.dATAPEDIDOField;
        }
        set {
            this.dATAPEDIDOField = value;
        }
    }
    
    /// <remarks/>
    public string NUMERODOPROCESSO {
        get {
            return this.nUMERODOPROCESSOField;
        }
        set {
            this.nUMERODOPROCESSOField = value;
        }
    }
    
    /// <remarks/>
    public string TELEFONE {
        get {
            return this.tELEFONEField;
        }
        set {
            this.tELEFONEField = value;
        }
    }
    
    /// <remarks/>
    public string NOMEINSTITUICAO {
        get {
            return this.nOMEINSTITUICAOField;
        }
        set {
            this.nOMEINSTITUICAOField = value;
        }
    }
    
    /// <remarks/>
    public string FORUMVARA {
        get {
            return this.fORUMVARAField;
        }
        set {
            this.fORUMVARAField = value;
        }
    }
    
    /// <remarks/>
    public string USUARIO {
        get {
            return this.uSUARIOField;
        }
        set {
            this.uSUARIOField = value;
        }
    }
    
    /// <remarks/>
    public string EMAIL {
        get {
            return this.eMAILField;
        }
        set {
            this.eMAILField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("INDIVIDUO", IsNullable=false)]
    public PESSOASINDIVIDUO[] INDISPONIBILIDADE {
        get {
            return this.iNDISPONIBILIDADEField;
        }
        set {
            this.iNDISPONIBILIDADEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("INDIVIDUO", IsNullable=false)]
    public PESSOASINDIVIDUO[] CANCELAMENTO {
        get {
            return this.cANCELAMENTOField;
        }
        set {
            this.cANCELAMENTOField = value;
        }
    }
    
    /// <remarks/>
    public string HASHVISUALIZACAO {
        get {
            return this.hASHVISUALIZACAOField;
        }
        set {
            this.hASHVISUALIZACAOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PESSOASINDIVIDUO {
    
    private string nOMEField;
    
    private string cPFCNPJField;
    
    private string[] iMOVEISField;
    
    /// <remarks/>
    public string NOME {
        get {
            return this.nOMEField;
        }
        set {
            this.nOMEField = value;
        }
    }
    
    /// <remarks/>
    public string CPFCNPJ {
        get {
            return this.cPFCNPJField;
        }
        set {
            this.cPFCNPJField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("MATRICULA", IsNullable=false)]
    public string[] IMOVEIS {
        get {
            return this.iMOVEISField;
        }
        set {
            this.iMOVEISField = value;
        }
    }
}
