INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (0, '');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (1, 'ACORDO EXTRAJUDICIAL');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (4, 'ALIENAÇÃO FIDUCIÁRIA');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (26, 'BEM DE FAMÍLIA');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (5, 'CESSÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (63, 'COMODATO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (6, 'COMPRA E VENDA');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (48, 'CONDOMÍNIO EDÍLICIO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (56, 'CONFERÊNCIA DE BENS');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (10, 'CONFISSÃO DE DÍVIDA/DAÇÃO EM PAGAMENTO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (58, 'CRÉDITO COM GARANTIA');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (14, 'DECLARAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (15, 'DECLARATÓRIA DE UNIÃO ESTÁVEL');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (16, 'DECLARATÓRIA DE UNIÃO ESTÁVEL HOMOAFETIVA');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (17, 'DESAPROPRIAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (52, 'DIREITO DE USO OU SUPERFICIE');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (55, 'DIRETIVAS ANTECIPADAS DE VONTADE (testamento vital)');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (20, 'DISSOLUÇÃO DE UNIÃO ESTÁVEL');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (21, 'DISTRATO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (53, 'DIVISÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (22, 'DOAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (23, 'EMANCIPAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (59, 'EMISSÃO DE CÉDULA');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (60, 'EMISSÃO DE DEBÊNTURES');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (54, 'FIANÇA');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (24, 'HIPOTECA');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (25, 'INCORPORAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (28, 'LOCAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (57, 'NOVAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (30, 'PACTO ANTENUPCIAL');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (49, 'PARCELAMENTO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (31, 'PENHOR');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (33, 'PROMESSA DE CESSÃO DE DIREITOS AQUISITIVOS');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (34, 'QUITAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (36, 'RECONHECIMENTO DE PATERNIDADE');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (38, 'REGISTRO DE CHANCELA MECÂNICA');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (39, 'REMISSÃO DE FORO E LAUDÊMIOS');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (62, 'RENUNCIA DE DIREITOS HEREDITÁRIOS');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (35, 'RERRATIFICAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (61, 'REVOGAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (43, 'SEM VALOR DECLARADO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (45, 'SERVIDÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (50, 'SOCIEDADE E FUNDAÇÕES');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (51, 'TRANSAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (46, 'USUFRUTO (reserva, instituição e renúncia)');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (70, 'PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (71, 'ARRENDAMENTO MERCANTIL (LEASING)');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (72, 'CONCESSÃO DE DOMÍNIO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (74, 'CONTRATO DE NAMORO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (75, 'CONCILIAÇÃO');
INSERT INTO CENSEC (CODIGO, DESCRICAO)
            VALUES (76, 'MEDIAÇÃO');

COMMIT WORK;