INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (1, 'ADITAMENTO', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (2, 'ADJUDICAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (3, 'ALIENAÇÃO DE DOMÍNIO UTIL', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (4, 'ALIENAÇÃO DE USUFRUTO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (5, 'AQUISIÇÃO DA NUA PROPRIEDADE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (6, 'AQUISIÇÃO DE DOMÍNIO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (7, 'ARREMATAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (8, 'ATA NOTARIAL', 'S', 'S', 8, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (9, 'CESSÃO DE BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (10, 'CESSÃO DE DIR. E PROM. COMPRA E VENDA BEIFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (11, 'CESSÃO DE DIREITOS', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (12, 'CESSÃO DE DIREITOS (SFH)', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (13, 'CESSÃO DE DIREITOS (SFI)', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (14, 'CESSÃO DE CRÉDITO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (15, 'CESSÃO DE DIREITOS AQUISITIVOS', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (16, 'CESSÃO DE DIREITOS HEREDITÁRIOS', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (17, 'CESSÃO DE HERANÇA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (18, 'CESSÃO DE LEGADO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (19, 'CESSÃO DE NUA PROPRIEDADE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (20, 'CESSÃO DE MEAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (21, 'CESSÃO DE MEAÇÃO E DE HERANÇA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (22, 'CESSÃO DE POSSE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (23, 'CESSÃO DE POSSE / PROM. CESSÃO BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (24, 'CESSÃO DE POSSE E COMPRA E VENDA BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (25, 'CESSÃO DE POSSE E PROM. COMPRA E VENDA BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (26, 'CESSÃO DE PROMESSA DE CESSÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (27, 'CESSÃO DE PROMESSA DE COMPRA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (28, 'CESSÃO DE USO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (29, 'CESSÃO DE USO DE SERVIDÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (30, 'CESSÃO DE USUFRUTO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (31, 'CESSÃO DE DIREITOS E ARREMATAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (32, 'CESSÃO E VENDA DE BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (33, 'CESSÃO FRAÇÃO TERRENO E COMPRA E VENDA BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (34, 'CESSÃO GRATUITA DE HERANÇA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (35, 'CESSÃO GRATUITA DE MEAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (36, 'CESSÃO GRATUITA DE MEAÇÃO E DE HERANÇA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (37, 'CISÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (38, 'CISÃO ANTECIPAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (39, 'COMODATO', 'N', 'N', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (40, 'COMPRA E VENDA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (41, 'COMPRA E VENDA (LEILÃO)', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (42, 'COMPRA E VENDA (SFH)', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (43, 'COMPRA E VENDA (SFI)', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (44, 'COMPRA E VENDA (COOPERATIVA)', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (45, 'COMPRA E VENDA (DOMÍNIO PLENO)', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (46, 'COMPRA E VENDA E CESSÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (47, 'COMPRA E VENDA E CESSÃO DIREITOS HEREDITÁRIOS', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (48, 'COMPRA E VENDA E DOAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (49, 'COMPRA E VENDA E DOAÇÃO COM RESERVA DE USUFRUTO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (50, 'COMPRA E VENDA FRAÇÃO TERRENO E PROM. COMPRA E VENDA BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (51, 'COMPROMISSO DE MANUTENÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (52, 'CONCESSÃO DE DIREITO REAL DE USO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (53, 'CONFISSÃO DE DÍVIDA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (54, 'CONFISSÃO DE DÍVIDA COM GARANTIA HIPOTECÁRIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (55, 'CONSOLIDAÇÃO DE PROPRIEDADE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (56, 'CONSTITUIÇÃO DE SERVIDÃO', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (57, 'CONTRATO DE CONSTRUÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (58, 'CONVENÇÃO DE CONDOMÍNIO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (59, 'CREMAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (60, 'DAÇÃO DE IMÓVEL EM PAGAMENTO DE DÍVIDA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (61, 'DAÇÃO EM PAGAMENTO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (62, 'DAÇÃO EM PAGAMENTO / NUA PROPRIEDADE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (63, 'DECLARATÓRIA', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (64, 'DESAPROPRIAÇÃO', 'S', 'N', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (65, 'DESINCORPORAÇÃO - ANTECIPAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (66, 'DESINCORPORAÇÃO PARTR. PESSOA JURÍDICA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (67, 'DISSOLUÇÃO DE SOCIEDADE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (68, 'DISSOLUÇÃO DE UNIÃO ESTÁVEL', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (69, 'DIVÓRCIO', 'N', 'S', 4, 'D');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (70, 'DIVÓRCIO E PARTILHA DE BENS', 'S', 'S', 4, 'D');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (71, 'DOAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (72, 'DOAÇÃO COM RESERVA DE USUFRUTO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (73, 'DOMÍNIO DIRETO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (74, 'EMANCIPAÇÃO', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (75, 'ENFITEUSE E SUB-ENFITEUSE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (76, 'EXTINÇÃO DE CONDOMÍNIO', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (77, 'EXTINÇÃO DE CONDOMÍNIO - ANTECIPAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (78, 'EXTINÇÃO DE CONDOMÍNIO - NUA PROPRIEDADE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (79, 'EXTINÇÃO DE FIDEICOMISSO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (80, 'EXTINÇÃO DE GRAVAME', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (81, 'EXTINÇÃO DE HIPOTECA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (82, 'EXTINÇÃO DE PESSOA JURÍDICA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (83, 'EXTINÇÃO DE USUFRUTO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (84, 'HIPOTECA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (85, 'INCORPORAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (86, 'INCORPORAÇÃO - ANTECIPAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (87, 'INCORPORAÇÃO - P/ REALIZAÇÃO DE CAPITAL', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (88, 'INSTITUIÇÃO DE BEM DE FAMÍLIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (89, 'INSTITUIÇÃO DE CONDOMÍNIO EDILÍCIO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (90, 'INSTITUIÇÃO DE USUFRUTO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (91, 'INSTITUIÇÃO DE USUFRUTO, USO E HABITAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (92, 'INVENTÁRIO E ADJUDICAÇÃO', 'S', 'S', 5, 'D');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (93, 'INVENTÁRIO E PARTILHA DE BENS', 'S', 'S', 5, 'D');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (95, 'MÚTUO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (96, 'MÚTUO COM ALIENAÇÃO FIDUCIÁRIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (97, 'MÚTUO COM GARANTIA HIPOTECÁRIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (98, 'PACTO ANTENUPCIAL', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (99, 'PERMUTA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (100, 'PERMUTA NUA PROPRIEDADE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (102, 'PROMESSA DE CESSÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (103, 'PROMESSA DE CESSÃO DE DIREITOS AQUISITIVOS', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (104, 'PROMESSA DE CESSÃO DE DIREITOS HEREDITÁRIOS', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (105, 'PROMESSA DE CESSÃO DE HERANÇA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (106, 'PROMESSA DE CESSÃO DE MEAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (107, 'PROMESSA DE CESSÃO DE MEAÇÃO E DE HERANÇA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (108, 'PROMESSA DE CESSÃO DE POSSE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (109, 'PROMESSA DE CESSÃO DE USUFRUTO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (110, 'PROMESSA DE CESSÃO E COMPRA E VENDA DE BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (111, 'PROMESSA DE CESSÃO E PROM. COMPRA E VENDA DE BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (112, 'PROMESSA DE CESSÃO POSSE E PROM. COMPRA E VENDA DE BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (113, 'PROMESSA DE CESSÃO POSSE E COMPRA E VENDA DE BENFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (114, 'PROMESSA DE COMPRA E VENDA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (115, 'PROMESSA DE COMPRA E VENDA - NUA PROPRIEDADE', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (116, 'PROMESSA DE COMPRA E VENDA E PROM. CESSÃO DIREITO HEREDITARIO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (117, 'PROMESSA DE COMPRA E VENDA FRAÇÃO TERR. E PROM. COMPRA E VENDA BEIFEITORIA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (118, 'PROMESSA DE COMPRA E VENDA COM QUITAÇÃO DE PREÇO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (119, 'PROMESSA DE COMPRA E VENDA E DAÇÃO EM PAGAMENTO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (120, 'PROMESSA DE VENDA E PROM. DE CESSÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (121, 'QUITAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (122, 'RATIFICAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (123, 'REMISSÃO (LEILÃO)', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (124, 'REMISSÃO DE FORO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (125, 'RENÚNCIA DE HERANÇA', 'S', 'S', 5, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (126, 'RENÚNCIA DE LEGADO', 'S', 'S', 5, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (127, 'RENÚNCIA DE MEAÇÃO', 'S', 'S', 5, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (128, 'RENÚNCIA DE USUFRUTO', 'S', 'S', 5, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (129, 'REPOSIÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (130, 'RE-RATIFICAÇÃO', 'N', 'S', 7, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (131, 'RESCISÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (132, 'DISTRATO NEGÓCIO JURID. TRIBU.', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (133, 'RESCISÃO PROMESSÃO DE CESSÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (134, 'RESTABELECIMENTO DA SOCIEDADE CONJUGAL', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (135, 'RETROVENDA', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (138, 'SEPARAÇÃO', 'N', 'S', 1, 'D');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (139, 'SEPARAÇÃO E PARTILHA DE BENS', 'S', 'S', 1, 'D');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (140, 'SENTENÇA JUDICIAL', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (143, 'TRANSAÇÃO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (144, 'TRANSF. DIREITOS S/ CONSTRUÇÃO TERRENO ALHEIO', 'S', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (145, 'UNIÃO ESTÁVEL', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (999, 'OUTROS', 'N', 'S', 1, 'E');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (-1, 'PROCURAÇÃO', 'N', 'N', -1, '*');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (-2, 'TESTAMENTO', 'N', 'N', -1, '*');
INSERT INTO NATUREZAS (CODIGO, DESCRICAO, DOI, CENSEC, CEP, TIPO)
               VALUES (0, '', 'N', 'S', 1, 'E');

COMMIT WORK;