INSERT INTO REGIMES (RegimesId, DESCRICAO, CENSEC)
             VALUES (1, 'COMUNHÃO DE BENS', 'Comunhão Universal');
INSERT INTO REGIMES (RegimesId, DESCRICAO, CENSEC)
             VALUES (3, 'COMUNHÃO PARCIAL DE BENS', 'Comunhão Parcial');
INSERT INTO REGIMES (RegimesId, DESCRICAO, CENSEC)
             VALUES (5, 'SEPARAÇÃO TOTAL DE BENS', NULL);
INSERT INTO REGIMES (RegimesId, DESCRICAO, CENSEC)
             VALUES (6, 'COMUNHÃO TOTAL DE BENS', NULL);
INSERT INTO REGIMES (RegimesId, DESCRICAO, CENSEC)
             VALUES (7, 'SEPARAÇÃO LEGAL DE BENS', 'Separação Total');
INSERT INTO REGIMES (RegimesId, DESCRICAO, CENSEC)
             VALUES (8, 'SEPARAÇÃO DE BENS', NULL);
INSERT INTO REGIMES (RegimesId, DESCRICAO, CENSEC)
             VALUES (9, 'COMUNHÃO UNIVERSAL DE BENS', 'Comunhão Universal');

COMMIT WORK;