INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (67, 'Casa');
INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (65, 'Apto');
INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (15, 'Loja');
INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (17, 'Sala/Conjunto');
INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (71, 'Terreno/fracao');
INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (31, 'Galpao');
INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (33, 'Predio Comercial');
INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (35, 'Predio Residencial');
INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (69, 'Fazenda/Sitio/Chacara');
INSERT INTO TIPOIMOVEL (CODIGO, DESCRICAO)
                VALUES (89, 'Outros');

COMMIT WORK;