INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (0, 1, '16', '1', '*', 'BUSCAS EM LIVROS OU PAPÉIS', 0.84);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (0, 2, '16', '2', '*', 'CERTIDÕES EXTRAÍDAS DE LIVROS', 19.26);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (0, 3, '16', '3', '*', 'APOSIÇÃO DE VISTO/INFORMAÇÃO VERBAL', 0);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (0, 4, '16', '4', '*', 'ARQUIVAMENTO/DESARQUIVAMENTO', 10.06);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (0, 5, '16', '5', '*', 'EXPEDIÇÃO E EMISSÃO DE GUIAS E COMUNICAÇÕES', 11.66);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (0, 6, '16', '6', '*', 'NOTIFICAÇÃO OU INTIMAÇÃO, POR PESSOA', 16.72);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 1, '17', '1', 'A', 'REGISTRO/AVERBAÇÃO ATÉ R$ 10.000,00', 153.53);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 2, '17', '1', 'B', 'REGISTRO/AVERBAÇÃO DE R$ 10.000,01 A R$ 30.000,00', 184.24);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 3, '17', '1', 'C', 'REGISTRO/AVERBAÇÃO DE R$ 30.000,01 A R$ 50.000,00', 214.95);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 4, '17', '1', 'D', 'REGISTRO/AVERBAÇÃO DE R$ 50.000,01 A R$ 70.000,00', 245.65);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 5, '17', '1', 'E', 'REGISTRO/AVERBAÇÃO DE R$ 70.000,01 A R$ 100.000,00', 291.73);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 6, '17', '1', 'F', 'REGISTRO/AVERBAÇÃO ACIMA DE R$ 100.000,00', 383.88);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 7, '17', '2', '*', 'REGISTRO/AVERBAÇÃO POR INSTRUMENTO, ATÉ 12 PÁGS., ASSOCIAÇÕES, ME E EPP...', 153.53);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 8, '17', '3', '*', 'REGISTRO DE MATRÍCULA DAS OFICINAS IMPRESSORAS... INCLUSIVE O ARQUIVAMENTO', 153.53);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 9, '17', '4', '*', 'REGISTRO DE LIVROS DE CONTABILIDADE (A CADA 200 PÁGS. OU FRAÇÃO)', 76.73);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 10, '17', '5', '*', 'REGISTRO DE LIVRO DIGITAL, POR LIVRO', 76.73);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 11, '17', '6', '*', 'CERTIDÕES, ATÉ 4 PÁGINAS', 73.73);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 12, '17', '7', '*', 'BUSCA PRÉVIA, POR NOMES', 18.37);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 13, '17', '8', '*', 'APRESENTAÇÃO DE TÍTULO PARA EXAME, LEGALIDADE OU CÁLCULO DE EMOL. S/ PRENOTAÇÃO', 63.38);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 14, '17', '9', '*', 'POR PÁG. EXCEDENTE A 4', 9.17);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 15, '17', '10', '*', 'VIA ADICIONAL, ATÉ 4 PÁGINAS', 42.16);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (7, 16, '17', '10', 'A', 'VIA ADICIONAL, POR PÁG. EXCEDENTE A 4', 9.17);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 1, '18', '1', 'A', 'PELO REGISTRO DE NASCIMENTO', 26.31);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 2, '18', '1', 'B', 'PELO REGISTRO DE ÓBITO', 26.31);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 3, '18', '2', 'A', 'PELO PROCESSO DE HABILITAÇÃO', 161.48);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 4, '18', '2', 'B', 'CASAMENTO CIVIL/CONVERSÃO DE UNIÃO ESTÁVEL EM CASAMENTO', 43);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 5, '18', '2', 'C', 'REG./INSC. DE CASAMENTO REL. C/ EFEITO CIVIL', 47.38);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 6, '18', '2', 'D', 'CASAMENTO FORA DA SEDE DO OFÍCIO', 405.14);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 7, '18', '2', 'E', 'CASAMENTO FORA DO DISTRITO SEDE DO CARTÓRIO', 459.91);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 8, '18', '2', 'F', 'AFIXAÇÃO DE EDITAL DE OUTRO OFÍCIO', 43);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 9, '18', '2', 'G', 'LAVRATURA DO ASSENTO DE CASAMENTO CERT. EXPEDIDA POR OUTRO OFÍCIO', 43);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 10, '18', '3', '*', 'TRANSC. DE NASC./CASAM./ÓB. DE BRASILEIROS OCORRIDOS NO EXTERIOR', 143.04);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 11, '18', '4', '*', 'RETIF./AVERB./TRANSC./CANC./RESTAUR. DE REGISTRO', 96.5);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 12, '18', '5', '*', 'AVERBAÇÃO DE PATERNIDADE', 45.89);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 13, '18', '6', '*', 'AVERB. POR CARTA DE SENTENÇA OU MANDADO', 63.14);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 14, '18', '7', '*', 'TERMO DE TUTELA OU CURATELA', 49.09);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 15, '18', '8', '*', 'PROCEDIMENTO DE CONVERSÃO DE UNIÃO ESTÁVEL EM CASAMENTO', 80.7);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 16, '18', '9', '*', 'SUPRIMENTO PARA CASAMENTO', 49.12);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 17, '18', '10', '*', 'CERTIDÃO (FOLHA COM 30 LINHAS)', 43.12);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 18, '18', '10', 'A', 'CERTIDÃO, POR FOLHA EXCEDENTE A UMA', 4.36);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 19, '18', '10', 'B', 'CERTIDÃO, BUSCA POR PERÍODO DE 5 ANOS', 4.36);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 20, '18', '11', '*', 'ARQUIVAMENTO/DESARQUIVAMENTO DE PROCURAÇÕES EM ATOS PRATICADOS NO RCPN', 10.06);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (3, 21, '18', '12', '*', 'AV. DE UNIÃO ESTÁVEL POR SENTENÇA JUDICIAL', 45.89);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 1, '20.1', '1', '1', 'REGISTRO SEM VALOR DECLARADO', 126.78);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 2, '20.1', '1', '2', 'REGISTRO ATÉ R$ 15000,00', 182.28);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 3, '20.1', '1', '3', 'REGISTRO ACIMA DE R$ 15.000,00 ATÉ R$ 30.000,00', 301.18);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 4, '20.1', '1', '4', 'REGISTRO ACIMA DE R$ 30.000,00 ATÉ R$ 45.000,00', 420.11);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 5, '20.1', '1', '5', 'REGISTRO ACIMA DE R$ 45.000,00 ATÉ R$ 60.000,00', 515.22);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 6, '20.1', '1', '6', 'REGISTRO ACIMA DE R$ 60.000,00 ATÉ R$ 80.000,00', 913.18);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 7, '20.1', '1', '7', 'REGISTRO ACIMA DE R$ 80.000,00 ATÉ R$ 100.000,00', 1078.07);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 8, '20.1', '1', '8', 'REGISTRO ACIMA DE R$ 100.000,00 ATÉ R$ 200.000,00', 1458.55);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 9, '20.1', '1', '9', 'REGISTRO ACIMA DE R$ 200.000,00 ATÉ R$ 400.000,00', 1569.56);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 10, '20.1', 'NI', '1', 'REGISTRO ACIMA DE R$ 400.000,00', 140.62);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 11, '20.2', '1', '1', 'MEMORIAL ATÉ R$ 100.000,00', 1182.13);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 12, '20.2', '1', '2', 'MEMORIAL DE R$ 100.000,01 ATÉ R$ 500.000,00', 1896.31);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 13, '20.2', '1', '3', 'MEMORIAL DE R$ 500.000,01 ATÉ R$ 800.000,00', 2638.3);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 14, '20.2', '1', '4', 'MEMORIAL DE R$ 800.000,01 ATÉ R$ 1.000.000,00', 3009.28);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 15, '20.2', 'NI', '*', 'MEMORIAL A PARTIR DE R$ 1.000.000,01', 140.62);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 16, '20.3', '1', '1', 'AVERBAÇÃO ATÉ R$ 15.000,00', 127.02);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 17, '20.3', '1', '2', 'AVERBAÇÃO DE R$ 15.000,01 ATÉ R$ 30.000,00', 160.07);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 18, '20.3', '1', '3', 'AVERBAÇÃO DE R$ 30.000,01 ATÉ R$ 45.000,00', 226.04);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 19, '20.3', '1', '4', 'AVERBAÇÃO DE R$ 45.000,01 ATÉ R$ 60.000,00', 259.18);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 20, '20.3', '1', '5', 'AVERBAÇÃO DE R$ 60.000,01 ATÉ R$ 80.000,00', 325.23);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 21, '20.3', '1', '6', 'AVERBAÇÃO DE R$ 80.000,01 ATÉ R$ 100.000,00', 396.54);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 22, '20.3', '1', '7', 'AVERBAÇÃO DE R$ 100.000,01 ATÉ R$ 200.000,00', 467.66);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 23, '20.3', '1', '8', 'AVERBAÇÃO DE R$ 200.000,01 ATÉ R$ 400.000,00', 508.88);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 24, '20.3', 'NI', '*', 'AVERBAÇÃO A PARTIR DE R$ 400.000,01', 70.3);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 25, '20.4', '1', '*', 'OUTRAS AVERBAÇÕES SEM CONTEÚDO/CANCELAMENTO DE PRENOTAÇÃO', 95.1);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 26, '20.4', '2', '*', 'AVERBAÇÕES DESMEMBRAMENTO/REMEMBRAMENTO', 317.06);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 27, '20.4', '3', '*', 'CERTIDÃO DE PRENOTAÇÃO', 20.57);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 28, '20.4', '4', '*', 'INTIMAÇÃO DE PROMISSÓRIO-COMPRADOR DE LOTEAMENTO', 29.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 29, '20.4', '5', 'A', 'CONVENÇÃO DE CONDOMÍNIO PELA 1ª UNIDADE', 120.45);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 30, '20.4', '5', 'B', 'CONVENÇÃO DE CONDOMÍNIO POR UNIDADE QUE ACRESCER A 1ª', 17.39);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 31, '20.4', '5', 'C', 'CONVENÇÃO DE CONDOMÍNIO POR REMISSÃO NAS MATRÍCULAS', 15.81);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 32, '20.4', '6', '*', 'CERTIDÃO DE ÔNUS REAIS E VINTENÁRIAS', 71.3);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 33, '20.4', '7', 'A', 'PELO PRIMEIRO RECEBIMENTO E ABERTURA DE CONTA', 5.84);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 34, '20.4', '7', 'B', 'PELO RECEBIMENTO DE CADA PRESTAÇÃO SEGUINTE', 1.23);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 35, '20.4', '8', 'A', 'ALIEN. FID.: INTIMAÇÃO PARA CONSTITUIÇÃO EM MORA', 63.38);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 36, '20.4', '8', 'B', 'ALIEN. FID.: POR PESSOA A MAIS, ALÉM DA PRIMEIRA', 29.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 37, '20.4', '8', 'C', 'ALIEN. FID.: EXPEDIÇÃO DE EDITAL - ALÉM DO CUSTO DA PUBLICAÇÃO', 29.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 38, '20.4', '8', 'D', 'ALIEN. FID.: RECEBIMENTO DE VALOR E REPASSE AO CREDOR', 29.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 39, '20.4', '9', 'A1', 'RETIFICAÇÃO (ART.213,II,LRP) AVERBAÇÃO', 285.32);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 40, '20.4', '9', 'A2', 'RETIFICAÇÃO (§2º ART.213,II,LRP) NOTIFICAÇÃO', 29.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 41, '20.4', '9', 'A3', 'RETIFICAÇÃO (§3º IN FINE ART.213,II,DA LRP) EDITAL', 29.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 42, '20.4', '9', 'B', 'RETIFICAÇÃO (ART.213,I,b,c,d,e,f,g,DA LRP)', 95.1);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 43, '20.4', '9', 'C', 'RETIFICAÇÃO NAS DEMAIS HIPÓTESES', 95.1);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 44, '20.4', '10', '*', 'OUTRAS INTIMAÇÕES/NOTIFICAÇÕES/COMUNICAÇÕES', 29.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 45, '20.4', '10', 'A', 'OUTRAS INTIMAÇÕES/NOTIFICAÇÕES/COMUNICAÇÕES P/ PÁG. EXC. A 3ª', 2.76);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 46, '20.4', '10', 'B', 'POR CORREIO ELETRÔNICO OU SIMILAR SEM LIMITAÇÃO DE PÁG.', 16.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 47, '20.4', '11', '*', 'EXAME DE LEGALIDADE OU CÁLCULO DE EMOLUMENTOS SEM PRENOTAÇÃO', 63.38);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 1, '21', 'A', '*', 'REGISTRO DAS SENTENÇAS DECLARATÓRIAS DE INSOLVÊNCIA OU DE FALÊNCIA...', 41.23);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 2, '21', 'B', '*', 'SENTENÇAS QUE DECRETAREM OU CESSAREM INTERDIÇÕES DE DIREITO PREVISTAS NA LEGISLA', 38.69);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 3, '21', 'C', '*', 'SENTENÇA DE CURATELA OU TUTELA', 38.69);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 10, '24', '1', 'J', 'PROTOCOLIZAÇÃO DE R$ 450,01 ATÉ 500,00', 123.14);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 11, '24', '1', 'K', 'PROTOCOLIZAÇÃO DE R$ 500,01 ATÉ 600,00', 147.81);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 12, '24', '1', 'L', 'PROTOCOLIZAÇÃO DE R$ 600,01 ATÉ 700,00', 172.47);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 13, '24', '1', 'M', 'PROTOCOLIZAÇÃO DE R$ 700,01 ATÉ 800,00', 197.03);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 14, '24', '1', 'N', 'PROTOCOLIZAÇÃO DE R$ 800,01 ATÉ 900,00', 221.68);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 15, '24', '1', 'O', 'PROTOCOLIZAÇÃO DE R$ 900,01 ATÉ 1.000,00', 246.34);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 16, '24', '1', 'P', 'PROTOCOLIZAÇÃO DE R$ 1.000,01 ATÉ 1.500,00', 277.05);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 17, '24', '1', 'Q', 'PROTOCOLIZAÇÃO DE R$ 1.500,01 ATÉ 2.000,00', 307.76);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 18, '24', '1', 'R', 'PROTOCOLIZAÇÃO DE R$ 2.000,01 ATÉ 2.500,00', 338.46);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 19, '24', '1', 'S', 'PROTOCOLIZAÇÃO DE R$ 2.500,01 ATÉ 3.000,00', 369.18);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 20, '24', '1', 'T', 'PROTOCOLIZAÇÃO DE R$ 3.000,01 ATÉ 3.500,00', 399.9);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 21, '24', '1', 'U', 'PROTOCOLIZAÇÃO DE R$ 3.500,01 ATÉ 4.000,00', 430.62);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 22, '24', '1', 'V', 'PROTOCOLIZAÇÃO DE R$ 4.000,01 ATÉ 4.500,00', 461.31);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 23, '24', '1', 'W', 'PROTOCOLIZAÇÃO DE R$ 4.500,01 ATÉ 5.000,00', 492.01);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 24, '24', '1', 'X', 'PROTOCOLIZAÇÃO DE R$ 5.000,01 ATÉ 7.500,00', 522.71);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 25, '24', '1', 'Y', 'PROTOCOLIZAÇÃO DE R$ 7.500,01 ATÉ 10.000,00', 553.42);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 26, '24', '1', 'Z', 'PROTOCOLIZAÇÃO ACIMA DE R$ 10.000,01', 584.14);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 27, '24', '2', '*', 'CANCELAMENTO DO PROTESTO/AVERBAÇÃO DA SUSTAÇÃO', 45.93);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 28, '24', '3', '1', 'CERTIDÃO FORNECIDA A CADA ENTIDADE REQUERENTE', 20.26);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 29, '24', '3', '2', 'A CADA NOME/DOCUMENTO RELACIONADO AO ITEM 24.3.1', 11.05);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 1, '25', '1', 'I', 'REGISTRO/AVERBAÇÃO ATÉ R$ 70.000,00', 77.32);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 2, '25', '1', 'A', 'PELAS 5 PRIMEIRAS PÁGINAS ATÉ R$ 70.000,00 (1% DO VALOR DECLARADO)', 0);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 3, '25', 'II', 'A', 'REGISTRO/AVERBAÇÃO DE R$ 70.000,01 A R$ 80.000,00', 387.27);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 4, '25', 'II', 'B', 'REGISTRO/AVERBAÇÃO DE R$ 80.000,01 A R$ 90.000,00', 420.58);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 5, '25', 'II', 'C', 'REGISTRO/AVERBAÇÃO DE R$ 90.000,01 A R$ 100.000,00', 453.84);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 6, '25', 'II', 'D', 'REGISTRO/AVERBAÇÃO DE R$ 100.000,01 A R$ 150.000,00', 520.47);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 7, '25', 'II', 'E', 'REGISTRO/AVERBAÇÃO DE R$ 150.000,01 A R$ 200.000,00', 564.85);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 8, '25', 'II', 'F', 'REGISTRO/AVERBAÇÃO ACIMA DE R$ 200.000,00', 613.29);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 9, '25', 'II', 'G', 'POR PÁG. EXCEDENTE A 5, MAIS DE R$ 70.000,00', 2.76);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 10, '25', 'II', 'H', 'POR VIA EXCEDENTE COM VALOR DECLARADO', 12.65);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 11, '25', 'II', 'I', 'SEM VALOR DECLARADO (INCLUSIVE ATAS) ATÉ 5 PÁGS.', 125.21);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 12, '25', 'III', '*', 'POR PÁGINA EXCEDENTE A 5, SEM VALOR DECLARADO', 2.76);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 13, '25', 'IV', '*', 'POR VIA EXCEDENTE, SEM VALOR DECLARADO', 12.65);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 14, '25', '2', '*', 'REGISTRO DE DOCUMENTO ÚNICO DE TANSFERÊNCIA - DUT', 18.99);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 15, '25', '3', '*', 'REGISTRO DE DECLARAÇÕES UNILATERAIS', 47.13);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 16, '25', '4', '*', 'REGISTRO DE MÍDIA DE DOCUMENTOS DIGITALIZADOS', 315.46);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 17, '25', '5', '*', 'SIMPLES CUSTÓDIA TEMPORÁRIA DE DOCUMENTOS', 0.11);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 18, '25', '5', 'OBS-1', 'POR PÁGINA EXCEDENTE A 15', 0.02);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 19, '25', '6', 'OBS-1', 'REGISTRO DE DOCUMENTOS PARA FINS DE CONSERVAÇÃO, ATÉ 4 PÁG.', 0.28);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 20, '25', '6', 'OBS-2', 'POR PÁGINA EXCEDENTE A 4', 0.04);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 21, '25', '7', 'A', 'REGISTRO DE EDITAIS ATÉ O LIMITE DE VALOR DA CARTA CONVITE', 315.46);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 22, '25', '7', 'B', 'REGISTRO DE EDITAIS ATÉ O LIMITE DE VALOR DA TOMADA DE PREÇOS', 521.56);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 23, '25', '7', 'C', 'REGISTRO DE EDITAIS ACIMA DO LIMITE DA TOMADA DE PREÇOS', 1014.64);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 24, '25', '7', 'OBS', 'POR PÁGINA EXCEDENTE A 10', 0.28);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 25, '25', '9.1', '*', 'REGISTRO DE NOTIFICAÇÃO, ATÉ 4 PÁGINAS', 144.25);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 26, '25', '9.1', 'A', 'POR PÁGINA EXCEDENTE A 4', 2.76);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 27, '25', '9.1', 'B', 'POR DILIGÊNCIA PESSOAL, ATÉ NO MÁXIMO 3', 18.99);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 28, '25', '9.2', '*', 'REGISTRO DE NOTIFICAÇÃO (POR MEIO ELETRÔNICO)', 20.57);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 29, '25', '9.2', 'A', 'POR PÁGINA EXCEDENTE A 4', 2.57);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 30, '25', '9.2', 'B', 'POR DILIGÊNCIA PESSOAL, ATÉ NO MÁXIMO 3', 18.99);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 31, '25', '9.3', '*', 'RECEPÇÃO DE NOTIFICAÇÃO (POR MEIO ELETRÔNICO)', 16.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 32, '25', '10', '*', 'DIGITALIZAÇÃO DE DOCUMENTOS', 7.87);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 33, '25', '10', 'A', 'POR PÁGINA EXCEDENTE A 10', 0.11);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 34, '25', '11', '*', 'REMESSA CERTIFICADA DE ARQUIVOS', 17.82);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 35, '25', '11', 'A', 'CERTIDÕES IMPRESSAS EM PAPEL ATÉ 2 PÁGINAS', 11.05);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 36, '25', '11', 'B', 'POR PÁGINA EXCEDENTE A 2, REMESSA CERTIFICADA DE ARQUIVOS', 1.52);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 37, '25', '12', '*', 'AUTENTICAÇÃO DE MICROFILME', 31.66);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 38, '25', '12', 'A', 'BUSCA E CERTIDÃO DE CÓPIA EXTRAÍDA DE MÍDIAS ATÉ 2 PÁG.', 11.05);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 39, '25', '12', 'B', 'POR PÁGINA EXCEDENTE', 1.52);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 40, '25', '12', 'C', 'AUTENTICAÇÃO DE CÓPIA EXTRAÍDA DE MICROFILME, POR PÁGINA', 3.12);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 41, '25', '12', 'D', 'AUTENTICAÇÃO DE CÓPIA EXTRAÍDA DE DISCO ÓTICO OU SEMELHANTE, POR PÁGINA', 1.52);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 42, '25', '13', 'A', 'CERTIDÕES EXTRAÍDAS DE REGISTROS OU PAPÉIS ARQUIVADOS ATÉ 2 PÁGINAS', 15.81);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 43, '25', '13', 'B', 'POR PÁGINA EXCEDENTE A 2, EXTRAÇÃO DE CERTIDÕES', 3.93);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 44, '25', 'NI', '5', 'EMOLUMENTOS DA AVERBAÇÃO (METADE DO VALOR DO REGISTRO OBJETIVADO)', 0);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 48, '20.4', '12', 'A', 'RECONHECIMENTO EXTRAJUDICIAL DE USUCAPIÃO: PELO PROCEDIMENTO', 161.48);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 49, '20.4', '12', 'B', 'RECONHECIMENTO EXTRAJUDICIAL DE USUCAPIÃO: POR NOTIFICAÇÃO/INTIMAÇÃO', 29.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 40, '22', '9', '*', 'MATERIALIZAÇÃO DE DOCUMENTOS', 10.85);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (5, 50, '20.4', '12', 'C', 'RECONHECIMENTO EXTRAJUDICIAL DE USUCAPIÃO: PELA CONFECÇÃO DE EDITAL', 29.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (6, 45, '25', 'NI', '11', 'A CADA R$ 100.000,00. ACIMA DE R$ 200.000,00', 88.79);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 4, '21', 'D', '*', 'TERMO DE CURATELA OU TUTELA', 36.56);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 5, '21', 'E', '*', 'TERMO DE CAUÇÃO, EM GARANTIA DE TUTELA OU CURATELA', 21.63);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 6, '21', 'F', '*', 'DAS AUTORIZAÇÕES, POR ALVARÁ OU PRECATÓRIA, QUE ENVOLVAM INTERESSES DE INCAPAZ', 21.63);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 7, '21', 'G', '*', 'EMANCIPAÇÃO, INCLUSIVE SENTENÇA QUANDO HOUVER, BEM COMO DE PESSOAS COM REGISTRO', 41.23);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 8, '21', 'H', '*', 'DE SENTENÇAS DECLARATÓRIAS DE AUSÊNCIA OU ABERTURA DE SUCESSÃO PROVISÓRIA OU DEF', 41.23);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 9, '21', 'I', '*', 'DOS CONTRATOS DE TUTELADOS OU CURATELADOS, QUER POR INSTRUMENTO PÚBLICO OU PARTI', 41.23);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 10, '21', 'J', '*', 'DE QUALQUER OUTRO ATO OU SENTENÇA SUJEITO A REGISTRO', 41.23);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 11, '21', 'K', '*', 'QUANDO HOUVER MAIS DE UM NOME NO PROCESSO DE TUTELA, POR NOME EXCEDENTE', 0.84);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 12, '21', 'L', '*', 'CERTIDÕES (FOLHA COM 30 LINHAS)', 28.49);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 13, '21', 'L', 'A', 'CERTIDÕES, POR FOLHA EXCEDENTE A UMA', 4.36);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (8, 14, '21', 'L', 'B', 'CERTIDÕES, BUSCA POR ASSUNTO, INDEPENDENTE DO PERÍODO', 8.68);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 1, '22', '1', '1', 'ESCRITURA ATÉ R$ 15.000,00', 182.28);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 2, '22', '1', '2', 'ESCRITURA DE R$ 15.000,01 ATÉ R$ 30.000,00', 301.18);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 3, '22', '1', '3', 'ESCRITURA DE R$ 30.000,01 ATÉ R$ 45.000,00', 420.11);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 4, '22', '1', '4', 'ESCRITURA DE R$ 45.000,01 ATÉ R$ 60.000,00', 515.22);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 5, '22', '1', '5', 'ESCRITURA DE R$ 60.000,01 ATÉ R$ 80.000,00', 913.18);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 6, '22', '1', '6', 'ESCRITURA DE R$ 80.000,01 ATÉ R$ 100.000,00', 1078.07);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 7, '22', '1', '7', 'ESCRITURA DE R$ 100.000.01 ATÉ R$ 200.000,00', 1458.55);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 8, '22', '1', '8', 'ESCRITURA DE R$ 200.000,01 ATÉ R$ 400.000,00', 1565.05);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 9, '22', '1.1', '*', 'ESC. DE INSTITUIÇÃO (ATÉ 10 UNIDADES)', 1272.73);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 10, '22', '1.1', 'A', 'POR UNIDADE EXCEDENTE (INSTITUIÇÃO DE CONDOMÍNIO)', 87.72);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 11, '22', '1.2', 'A', 'RECONHECIMENTO DE PATERNIDADE', 96.69);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 12, '22', '1.2', 'B', 'ESC. DE SEPARAÇÃO CONSENSUAL/INV. NEGATIVO', 253.62);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 13, '22', '1.3', '*', 'ESCRITURAS DE QUITAÇÃO E RESCISÃO', 96.69);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 14, '22', '1.4', '*', 'ESC. DE CONVENÇÃO DE CONDOMÍNIO', 134.72);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 15, '22', '1.4', 'A', 'POR UNIDADE EXCEDENTE (CONVENÇÃO DE CONDOMÍNIO)', 15.81);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 16, '22', '2', 'A', 'PROCURAÇÃO PARA FINS PREVIDENCIÁRIOS', 16.6);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 17, '22', '2', 'B', 'PROCURAÇÃO SOBRE BENS MÓVEIS E IMÓVEIS', 237.77);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 18, '22', '2', 'C', 'PROCURAÇÃO EM CAUSA PRÓPRIA', 0);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 19, '22', '2', 'D', 'PROCURAÇÃO, REVOGAÇÃO OU SUBSTABELECIMENTO', 49.09);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 20, '22', '2.1', '*', 'POR OUTORGANTE EXCEDENTE A 3 (PROCURAÇÃO)', 7.87);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 21, '22', '3', 'A', 'RECONHECIMENTO DE FIRMA POR AUTENTICIDADE', 5.41);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 22, '22', '3', 'B', 'RECONHECIMENTO DE FIRMA POR SEMELHANÇA OU CHANCELA', 5.26);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 23, '22', '3', 'C', 'ABERTURA DE FIRMA', 11.72);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 24, '22', '4', '*', 'AUTENTICAÇÃO POR DOCUMENTO OU PÁGINA', 5.42);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 25, '22', '5', 'I-A', 'TESTAMENTO CERRADO - APROVAÇÃO', 259.97);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 26, '22', '5', 'I-B', 'TESTAMENTO CERRADO SE ESCRITO POR TABELIAO A ROGO', 380.48);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 27, '22', '5', 'II', 'TESTAMENTO PÚBLICO (LAVRATURA/TRASLADO)', 380.48);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 28, '22', '5', 'II-A', 'TESTAMENTO PÚBLICO (MONTEPIO/PECÚLIO)', 126.78);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 29, '22', '5', 'II-B', 'TESTAMENTO PÚBLICO, APENAS PARA REVOGAÇÃO', 119);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 30, '22', '6', '*', 'ATA NOTARIAL SEM VALOR (PELA 1ª FOLHA)', 158.5);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 31, '22', '6', 'A', 'POR PÁGINA EXCEDENTE A 1 (ATA SEM VALOR)', 23.73);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 32, '22', '7', '1', 'ATA NOTARIAL ATÉ R$ 15.000,00', 182.28);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 33, '22', '7', '2', 'ATA NOTARIAL DE R$ 15.000,01 ATÉ R$ 30.000,00', 301.18);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 34, '22', '7', '3', 'ATA NOTARIAL DE R$ 30.000,01 ATÉ R$ 45.000,00', 420.11);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 35, '22', '7', '4', 'ATA NOTARIAL DE R$ 45.000,01 ATÉ R$ 60.000,00', 515.22);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 36, '22', '7', '5', 'ATA NOTARIAL DE R$ 60.000,01 ATÉ R$ 80.000,00', 913.18);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 37, '22', '7', '6', 'ATA NOTARIAL DE R$ 80.000,01 ATÉ R$ 100.000,00', 1078.07);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 38, '22', '7', '7', 'ATA NOTARIAL DE R$ 100.000.01 ATÉ R$ 200.000,00', 1458.55);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 39, '22', '7', '8', 'ATA NOTARIAL DE R$ 200.000,01 ATÉ R$ 400.000,00', 1565.05);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 41, '22', 'NI', '8', '1ª AQUISIÇÃO SFH (50% DOS EMOLUMENTOS N/ FUNDOS)', 0);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 42, '22', 'NI', '13', 'DILIGÊNCIA, 50% DO VALOR ORIGINÁRIO', 0);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (2, 43, '22', 'NI', '20', 'A CADA R$ 100.000,00 ACIMA DE R$ 400.000,00', 140.62);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 1, '24', '1', 'A', 'PROTOCOLIZAÇÃO DE R$ 0,01 ATÉ 50,00', 12.24);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 2, '24', '1', 'B', 'PROTOCOLIZAÇÃO DE R$ 50,01 ATÉ 100,00', 24.62);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 3, '24', '1', 'C', 'PROTOCOLIZAÇÃO DE R$ 100,01 ATÉ 150,00', 36.88);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 4, '24', '1', 'D', 'PROTOCOLIZAÇÃO DE R$ 150,01 ATÉ 200,00', 49.27);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 5, '24', '1', 'E', 'PROTOCOLIZAÇÃO DE R$ 200,01 ATÉ 250,00', 61.55);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 6, '24', '1', 'F', 'PROTOCOLIZAÇÃO DE R$ 250,01 ATÉ 300,00', 73.83);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 7, '24', '1', 'G', 'PROTOCOLIZAÇÃO DE R$ 300,01 ATÉ 350,00', 86.22);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 8, '24', '1', 'H', 'PROTOCOLIZAÇÃO DE R$ 350,01 ATÉ 400,00', 98.49);
INSERT INTO TABELACUSTAS (ATRIBUICAO, ORDEM, TABELA, ITEM, SUBITEM, DESCRICAO, VALOR)
                  VALUES (4, 9, '24', '1', 'I', 'PROTOCOLIZAÇÃO DE R$ 400,01 ATÉ 450,00', 110.77);

COMMIT WORK;